### ISSUE TITLE
dt_mssql class does not function on PHP >=7.0.0

### ISSUE THREAD

**Issue by kczx3** [phpopenfw/phpOpenFW2#2]
The mssql_* functions were removed in PHP 7.0.0 thus this driver will not function anymore.  Easiest switch would be to migrate to using the Microsoft maintained sqlsrv_* functions.

**Comment by phpopenfw** [comment]
Yes, you are correct. phpOpenFW2 does work with PHP 5.4+ so that is why the mssql drivers are still there. There is also an sqlsrv driver as well which can be used if you are using PHP 7+. phpOpenFW v3 will be PHP 7+ only and all non-PHP 7 functionality will be removed (old mysql driver, mssql, etc.).

**Comment by kczx3** [comment]
So really this framework only works with PHP >= 5.4 and < 7.  Maybe that's the typical understanding when you say "5.4+" however I interpreted that as anything above 5.4, including major version increments.  Guess I will have to fork this and make my own modifications considering our new application servers were all setup to run PHP 7.2...

**Comment by phpopenfw** [comment]
You do not need to fork and modify for PHP 7.x compatibility as that is already there. It supports everything from PHP 5.4 on upward (5.4, 5.5, 5.6, 7.0, 7.1, 7.2, etc). We have it running on servers with PHP 5.6, 7.0, 7.1, and 7.2. The sqlsrv driver works on all versions of PHP >= 5.4, including 7.x. The mssql driver is simply a legacy driver and works with everything >= PHP 5.4 and < PHP 7. It is still there to support older applications.
